id: P003233
initial_creation_type: ocr
source_metadata:
  id: bdr:W20010
  title: སྨན་གྱི་རྩ་རྒྱུད་ཀྱི་འགྲེལ་པ
  author: ''
  volumes:
    6b7ccc9afe4f4ff1a0015bd6313de827:
      image_group_id: I1PD372
      title: ''
      volume_number: 1
      total_pages: 212
